/* DO NOT EDIT THIS FILE - it is machine generated */
#include <JavaVM/jni.h>
/* Header for class org_lwjgl_opengl_awt_PlatformMacOSXGLCanvas */

#ifndef _Included_org_lwjgl_opengl_awt_PlatformMacOSXGLCanvas
#define _Included_org_lwjgl_opengl_awt_PlatformMacOSXGLCanvas
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_lwjgl_opengl_awt_PlatformMacOSXGLCanvas
 * Method:    createView
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_org_lwjgl_opengl_awt_PlatformMacOSXGLCanvas_createView
  (JNIEnv *, jobject, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
