/* DO NOT EDIT THIS FILE - it is machine generated */
#include <JavaVM/jni.h>
/* Header for class org_lwjgl_vulkan_awt_PlatformMacOSXVKCanvas */

#ifndef _Included_org_lwjgl_vulkan_awt_PlatformMacOSXVKCanvas
#define _Included_org_lwjgl_vulkan_awt_PlatformMacOSXVKCanvas
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_lwjgl_vulkan_awt_PlatformMacOSXVKCanvas
 * Method:    createMTKView
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_org_lwjgl_vulkan_awt_PlatformMacOSXVKCanvas_createMTKView
  (JNIEnv *, jobject, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
